export const REQUEST_PAPERS = "REQUEST PAPERS";
export const LOADING_PAPERS = "LOADING PAPERS";
export const PAPERS_LOADING_SUCCESS = "PAPERS LOADED SUCCESFULLY";
export const PAPERS_LOADING_ERROR = "ERROR IN LOADING PAPER";
